basePath: /
definitions:
  dto.CopyCardToDeckRequest:
    properties:
      card_id:
        type: string
      deck_id:
        type: string
    required:
    - card_id
    - deck_id
    type: object
  dto.CopyCardToDeckResponse:
    properties:
      card:
        $ref: '#/definitions/entity.Card'
    type: object
  dto.CopyDeckRequest:
    properties:
      deck_id:
        type: string
    required:
    - deck_id
    type: object
  dto.CopyDeckResponse:
    properties:
      deck:
        $ref: '#/definitions/entity.DeckWithCards'
      deck_review:
        $ref: '#/definitions/entity.DeckWithReviewCards'
    type: object
  dto.CreateCardRequest:
    properties:
      answer:
        type: string
      deck_id:
        type: string
      index:
        type: integer
      question:
        type: string
      question_img_label:
        type: string
      question_img_url:
        type: string
      wrong_answers:
        items:
          type: string
        type: array
    required:
    - answer
    - deck_id
    - question
    - wrong_answers
    type: object
  dto.CreateCardResponse:
    properties:
      card:
        $ref: '#/definitions/entity.Card'
    type: object
  dto.CreateDeckRequest:
    properties:
      description:
        type: string
      description_img_url:
        type: string
      name:
        type: string
      position:
        type: string
      total_cards:
        type: integer
    required:
    - name
    type: object
  dto.CreateDeckResponse:
    properties:
      deck:
        $ref: '#/definitions/entity.Deck'
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.SignupResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.UpdateCardRequest:
    properties:
      answer:
        type: string
      card_id:
        type: string
      deck_id:
        type: string
      question:
        type: string
      question_img_label:
        type: string
      question_img_url:
        type: string
      wrong_answers:
        items:
          type: string
        type: array
    required:
    - card_id
    type: object
  dto.UpdateCardResponse:
    properties:
      card:
        $ref: '#/definitions/entity.Card'
      success:
        type: boolean
    type: object
  dto.UpdateDeckRequest:
    properties:
      cur_new_cards:
        type: integer
      cur_review_cards:
        type: integer
      deck_id:
        type: string
      description:
        type: string
      description_img_url:
        type: string
      is_favorite:
        type: boolean
      is_public:
        type: boolean
      last_review:
        type: string
      max_new_cards:
        type: integer
      max_review_cards:
        type: integer
      name:
        type: string
      position:
        type: string
      rating:
        type: number
      total_learned_cards:
        type: integer
      views:
        type: integer
    required:
    - deck_id
    type: object
  dto.UpdateDeckResponse:
    properties:
      deck:
        $ref: '#/definitions/entity.Deck'
      success:
        type: boolean
    type: object
  dto.UpdateUserRequest:
    properties:
      name:
        type: string
      new_password:
        type: string
      old_password:
        type: string
    type: object
  dto.UpdateUserResponse:
    properties:
      user:
        $ref: '#/definitions/entity.User'
    type: object
  entity.Card:
    properties:
      answer:
        type: string
      card_type:
        type: integer
      created_at:
        type: string
      deck_id:
        type: string
      id:
        type: string
      index:
        type: integer
      last_review:
        type: string
      next_review:
        type: string
      num_reviews:
        type: integer
      question:
        type: string
      question_img_label:
        type: string
      question_img_url:
        type: string
      sm2_ef:
        type: number
      sm2_i:
        type: integer
      sm2_n:
        type: integer
      user_id:
        type: string
      wrong_answers:
        items:
          type: string
        type: array
    type: object
  entity.Deck:
    properties:
      created_at:
        type: string
      cur_new_cards:
        type: integer
      cur_review_cards:
        type: integer
      description:
        type: string
      description_img_url:
        type: string
      id:
        type: string
      is_favorite:
        type: boolean
      is_public:
        type: boolean
      last_review:
        type: string
      max_new_cards:
        type: integer
      max_review_cards:
        type: integer
      name:
        type: string
      position:
        type: string
      rating:
        type: number
      total_cards:
        type: integer
      total_learned_cards:
        type: integer
      user_id:
        type: string
      views:
        type: integer
    type: object
  entity.DeckWithCards:
    properties:
      cards:
        items:
          $ref: '#/definitions/entity.Card'
        type: array
      created_at:
        type: string
      cur_new_cards:
        type: integer
      cur_review_cards:
        type: integer
      description:
        type: string
      description_img_url:
        type: string
      id:
        type: string
      is_favorite:
        type: boolean
      is_public:
        type: boolean
      last_review:
        type: string
      max_new_cards:
        type: integer
      max_review_cards:
        type: integer
      name:
        type: string
      num_blue_cards:
        type: integer
      num_green_cards:
        type: integer
      num_red_cards:
        type: integer
      position:
        type: string
      rating:
        type: number
      total_cards:
        type: integer
      total_learned_cards:
        type: integer
      user_id:
        type: string
      views:
        type: integer
    type: object
  entity.DeckWithReviewCards:
    properties:
      cards:
        items:
          $ref: '#/definitions/entity.Card'
        type: array
      created_at:
        type: string
      cur_new_cards:
        type: integer
      cur_review_cards:
        type: integer
      description:
        type: string
      description_img_url:
        type: string
      id:
        type: string
      is_favorite:
        type: boolean
      is_public:
        type: boolean
      last_review:
        type: string
      max_new_cards:
        type: integer
      max_review_cards:
        type: integer
      name:
        type: string
      num_blue_cards:
        type: integer
      num_green_cards:
        type: integer
      num_red_cards:
        type: integer
      position:
        type: string
      rating:
        type: number
      total_cards:
        type: integer
      total_learned_cards:
        type: integer
      user_id:
        type: string
      views:
        type: integer
    type: object
  entity.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      hashed_password:
        type: string
      id:
        type: string
      is_admin:
        type: boolean
      last_streak:
        type: string
      level:
        type: integer
      name:
        type: string
      streak:
        type: integer
      xp:
        type: integer
      xp_to_level_up:
        type: integer
    type: object
info:
  contact:
    email: hynduf@gmail.com
    name: API Support
  description: Backend server for VietCard application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VietCard Backend API
  version: "1.0"
paths:
  /api/card/copy:
    post:
      consumes:
      - application/json
      description: Copy Card To Deck
      parameters:
      - description: Copy Card To Deck Request
        in: body
        name: copy_card_to_deck_request
        required: true
        schema:
          $ref: '#/definitions/dto.CopyCardToDeckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CopyCardToDeckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Copy Card To Deck
      tags:
      - card
  /api/card/create:
    post:
      consumes:
      - application/json
      description: Create New Card
      parameters:
      - description: Create Card Request
        in: body
        name: create_card_request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateCardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New Card
      tags:
      - card
  /api/card/update:
    put:
      consumes:
      - application/json
      description: Update Card Details
      parameters:
      - description: Update Card Request
        in: body
        name: update_card_request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateCardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Card Details
      tags:
      - card
  /api/deck/copy:
    post:
      consumes:
      - application/json
      description: Copy Deck
      parameters:
      - description: Copy Deck Request
        in: body
        name: copy_deck_request
        required: true
        schema:
          $ref: '#/definitions/dto.CopyDeckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CopyDeckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Copy Deck
      tags:
      - deck
  /api/deck/create:
    post:
      consumes:
      - application/json
      description: Create New Deck
      parameters:
      - description: Create Deck Request
        in: body
        name: create_deck_request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDeckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateDeckResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New Deck
      tags:
      - deck
  /api/deck/update:
    put:
      consumes:
      - application/json
      description: Update Deck Details
      parameters:
      - description: Update Deck Request
        in: body
        name: update_deck_request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateDeckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateDeckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Deck Details
      tags:
      - deck
  /api/login:
    post:
      consumes:
      - multipart/form-data
      description: Login
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login
      tags:
      - user
  /api/signup:
    post:
      consumes:
      - multipart/form-data
      description: Sign Up
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Sign Up
      tags:
      - user
  /api/user/update:
    put:
      consumes:
      - application/json
      description: Update User Details
      parameters:
      - description: Update User Request
        in: body
        name: update_user_request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update User Details
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
